[package]
name = "labrinth"
version = "0.1.0"
#Team members, please add your emails and usernames
authors = ["geometrically <jai.a@tuta.io>", "Redblueflame <contact@redblueflame.com>", "Aeledfyr <aeledfyr@gmail.com>", "Charalampos Fanoulis <yo@fanoulis.dev>"]
edition = "2018"

[[bin]]
name = "labrinth"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-files = "0.4.0"
actix-multipart = "0.3.0"
actix-cors = "0.4.1"

meilisearch-sdk = "0.3.0"
reqwest = { version = "0.10.8", features = ["json"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7.3"
base64 = "0.13.0"
sha1 = { version = "0.6.0", features = ["std"] }

gumdrop = "0.8.0"
dotenv = "0.15"
log = "0.4.8"
env_logger = "0.8.1"
thiserror = "1.0.21"
lazy_static = "1.4.0"

futures = "0.3.6"
futures-timer = "3.0.2"
rust-s3 = "0.26.1"
async-trait = "0.1.41"

[dependencies.sqlx]
git = "https://github.com/launchbadge/sqlx/"
branch = "master"
default-features = false
features = ["runtime-actix", "postgres", "chrono", "offline", "macros", "migrate"]

[dependencies.sqlx-macros]
git = "https://github.com/launchbadge/sqlx/"
branch = "master"
default-features = false
features = ["runtime-actix", "postgres", "chrono", "offline"]

[dependencies.actix-ratelimit]
# Temp until actix-ratelimit bumps version on cargo
git = "https://github.com/TerminalWitchcraft/actix-ratelimit"
rev = "870822067dfeae7cc0304352d81c4cb79ee27f5a"
