[package]
name = "labrinth"
version = "0.1.0"
#Team members, please add your emails and usernames
authors = ["geometrically <jai.a@tuta.io>", "Redblueflame <contact@redblueflame.com>", "Aeledfyr <aeledfyr@gmail.com>", "Charalampos Fanoulis <yo@fanoulis.dev>"]
edition = "2018"

[[bin]]
name = "labrinth"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.1"
actix-files = "0.2.2"
actix-multipart = "0.2.0"
actix-cors = "0.2.0"

meilisearch-sdk = "0.3.0"

reqwest = {version="0.10.6", features=["json"]}

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7"

gumdrop = "0.8"
dotenv = "0.15"
log = "0.4.8"
env_logger = "0.7.1"

thiserror = "1.0.20"
async-trait = "0.1.36"

futures = "0.3.5"
futures-timer = "3.0.2"

base64 = "0.12.3"
sha1 = {version="0.6.0", features=["std"]}

[dependencies.sqlx]
git = "https://github.com/launchbadge/sqlx/"
branch = "master"
default-features = false
features = ["runtime-actix", "postgres", "chrono", "offline", "macros"]

[dependencies.sqlx-macros]
git = "https://github.com/launchbadge/sqlx/"
branch = "master"
default-features = false
features = ["runtime-actix", "postgres", "chrono", "offline"]
