version: '3'
services:
  postgres_db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: labrinth
      POSTGRES_PASSWORD: this_is_really_secret
  meilisearch:
    image: getmeili/meilisearch
    restart: on-failure
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@modrinth.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8070:80"
    links:
      - "postgres_db:pgsql-server"
volumes:
  meilisearch-data:
  db-data: