version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: toor
      MONGO_INITDB_ROOT_PASSWORD: modrinthadmin
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: toor
      ME_CONFIG_MONGODB_ADMINPASSWORD: modrinthadmin
      ME_CONFIG_OPTIONS_EDITORTHEME: material
  meilisearch:
    image: getmeili/meilisearch
    restart: on-failure
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms
volumes:
  meilisearch-data:
    external: true
  mongodb-data:
    external: true