name: Docker image build

on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the short sha
        id: short_sha
        run: echo ::set-output name=SHA::$(echo $GITHUB_SHA | cut -c1-8)
      - run: echo $TAG
        env:
          TAG: ${{ steps.short_sha.outputs.SHA }}
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: labrinth
          tag: ${{ steps.short_sha.outputs.SHA }}