name: Rust building

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get build cache
          id: cache-build
          uses: actions/cache@v2
          with:
            path: target/**
            key: ${{ runner.os }}-build-cache
      - name: Build
        run: cargo build --verbose